name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    if: github.repository_owner == 'IntellectualSites'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build
      - name: build plugins
        uses: actions/upload-artifact@main
        with:
          name: ps
          path: build/libs/ps.jar
      
